
name: dashboard

services:
  mongo:
    container_name: mongodb
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dashboard

  redis-stack:
    container_name: redis
    image:  redis/redis-stack:latest
    ports:
       - "6379:6379"
       - "8001:8001"
    volumes:
    - redis-data:/data
    networks:
      - dashboard
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    container_name: chapter-api
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis-stack
    networks:
      - dashboard
    command: npm run dev

volumes:
  mongo-data:
  redis-data:

networks:
  dashboard:
    driver: bridge